meta-facebook: minerva: Add initial GPIO setting
add plat-tool and plat-svc to initial GPIO setting by following minerva CMM
hardware setting

Change-Id: Iaa65aebd066339b73283402ddc638e2dda27e197

diff --git a/meta-facebook/meta-minerva/recipes-minerva/plat-tool/files/minerva-common-functions b/meta-facebook/meta-minerva/recipes-minerva/plat-tool/files/minerva-common-functions
--- a/meta-facebook/meta-minerva/recipes-minerva/plat-tool/files/minerva-common-functions
+++ b/meta-facebook/meta-minerva/recipes-minerva/plat-tool/files/minerva-common-functions
@@ -4,21 +4,21 @@ set_gpio()
 {
     local NET_NAME=$1
     local OUT_VAL=$2
-    mapfile -t -d " " GPIO_INFO < <(gpiofind "$NET_NAME")
+    mapfile -t -d " " GPIO_INFO < <(gpiofind "${NET_NAME}")
     if [ "${#GPIO_INFO[@]}" -ne 2 ]; then
-        echo "set_gpio: can not find gpio, $NET_NAME"
+        logger -p user.info "set_gpio: can not find gpio, ${NET_NAME}"
         return 1
     fi
 
-    echo -n "set_gpio: set $NET_NAME = $OUT_VAL"
-    if ! gpioset "${GPIO_INFO[0]}" "${GPIO_INFO[1]%$'\n'}"="$OUT_VAL"; then
-        echo " failed"
+    
+    if ! gpioset "${GPIO_INFO[0]}" "${GPIO_INFO[1]%$'\n'}"="${OUT_VAL}"; then
+        logger -p user.info " failed"
         return 1
     fi
-
-    echo " success"
+    logger -p user.info "set_gpio: set ${NET_NAME} = ${OUT_VAL} success"
     return 0
 }
+
 
 get_gpio()
 {
